name: "Release: Publish"
run-name: "Release: ${{ github.event.head_commit.message || inputs.tag }}"

on:
  push:
    branches:
      - mainline
    paths:
      - CHANGELOG.md
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: Specify a tag to re-run a release.

concurrency:
  group: release

permissions:
  contents: read

jobs:
  Release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      id-token: write
      contents: write
    environment: release
    steps:
      - name: Generate Release Notes
        run: |
          {
            echo 'RELEASE_NOTES<<EOF'
            python .github/scripts/get_latest_changelog.py
            echo EOF
          } >> $GITHUB_ENV
      - name: PushRelease
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          gh release create $TAG -t "$TAG" --notes "$RELEASE_NOTES"
